<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PyramidTreasureConsoleRPG</RootNamespace>
    <AssemblyName>PyramidTreasureConsoleRPG</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests/**;tools/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Audio\ancient_egypt.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

</Project>
